### ISSUE TITLE
Ckfinder 

### ISSUE THREAD

**Issue by bhavanai13** [ckfinder/ckfinder-docs-samples-php#2]
i wanted to re-size image when it is uploaded by ckeditor .
we tried to do change on this file /ckfinder/config.php by changing cofig settings
$config['Images'] = Array(
		'maxWidth' => 660,
		'maxHeight' => 660,
		'quality' => 90);
But in our case we need to fix only width of image and height should vary as per aspect ratio.
but when i comment 'maxHeight' or i set 'maxHeight' => 0 it is not working.
can you please give me solution on above change ?
![ckeditor_change](https://user-images.githubusercontent.com/29423320/27122567-c1ab6b12-5108-11e7-8d7a-d4189d94437f.png)

**Comment by zaak** [comment]
Hi @bhavanai13. This repository contains documentation samples for CKFinrer 3, so this is not the right place to report issues related for CKFinder 2. It looks like a configuration issue. With CKFinder license you can ask for help our [customer support](https://cksource.com/contact).

**Comment by bhavanai13** [comment]
thank you @zaak 
i will post this issue on right place.
